export default {
	emailVerification: {
		email: null,
	},
	mobileVerification: {
		mobile: null,
	},
	TInformation: {
		firstName: null,
		lastName: null,
	},
	passwordVerification: {
		password: null,
	},
	accountInformation: {
		email: null,
		password: null,
	},
	personalInformation: {
		fullName: null,
		gender: null,
		dob: null,
		address: null,
		country: null,
		city: null,
		zipCode: null,
		nationality: null,
		mobile: null,
		homePhone: null,
		ssn: null,
		taxNumber: null,
	},
	companyInformation: {
		fullName: null,
		companyName: null,
		companyEmail: null,
		address: null,
		country: null,
		city: null,
		zipCode: null,
		industry: null,
		organization: null,
		noOfEmployees: null,
		mobile: null,
		phone: null,
		companyWebsite: null,
		yTunnus: null,
		companyDescription: null,
	},
	isLoginModelOpen: false,
	isJobSeekerModelOpen: false,
	seekForGig: false,
	isLoginModelOpenNew: false,
	isRegisterModelOpen: false,
	isForgotPasswordModelOpen: false,
	user: null,
	activityPoints:null,
	userType: '',
	userHeaderPanel: '',
	userLogged: false,
	TeamMemberList: [],
	TeamMember: [],
	userProfile: {},
	incompleteProfileFlag: null,
	firstTimeLogin: false,
	maintanceModeChecked: false,
	forgotPassFlag:null
};
